linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - goerr113
    - testpackage
    - thelper

issues:
  exclude-use-default: false
  exclude:
    - are missing in URL # exhaustivestruct
    - does not use range value # paralleltest
    - don't use underscores in Go names # golint and revive
    - should not use underscores in Go names # stylecheck
